name       : haskell-semigroupoids
version    : 5.3.4
release    : 5
source     :
    - https://hackage.haskell.org/package/semigroupoids-5.3.4/semigroupoids-5.3.4.tar.gz : 00d2e48973c3ab0a5d52616728ed63d0509454c8328148f698720014d7c58964
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides a wide array of (semi)groupoids and operations for working with them.
description: |
    Provides a wide array of (semi)groupoids and operations for working with them.
builddeps  :
    - haskell-bifunctors-devel
    - haskell-cabal-install
    - haskell-unordered-containers-devel
rundeps    :
    - devel:
        - haskell-bifunctors-devel
        - haskell-unordered-containers-devel
networking : yes
setup      : |
    # sed -i "s|Custom|Simple|" semigroupoids.cabal
    # sed -i "s|< 0.6|< 0.7|g" semigroupoids.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
