name       : haskell-semigroupoids
version    : 5.2.2
release    : 2
source     :
    - http://hackage.haskell.org/package/semigroupoids-5.2.2/semigroupoids-5.2.2.tar.gz : e4def54834cda65ac1e74e6f12a435410e19c1348e820434a30c491c8937299e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides a wide array of (semi)groupoids and operations for working with them.
description: |
    Provides a wide array of (semi)groupoids and operations for working with them.
builddeps  :
    - ghc-devel
    - haskell-bifunctors
    - haskell-cabal-install
    - haskell-comonad
    - haskell-distributive
    - haskell-hashable
    - haskell-transformers-compat
    - haskell-unordered-containers
setup      : |
    sed -i "s|< 0.6|< 0.7|g" semigroupoids.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
