name       : haskell-semigroupoids
version    : 5.1
release    : 1
source     :
    - http://hackage.haskell.org/package/semigroupoids-5.1/semigroupoids-5.1.tar.gz : 16ac8ce9b40b0407cdb1b1197a704ec58ec689d5a6de891165a577725361f835
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides a wide array of (semi)groupoids and operations for working with them.
description: |
    Provides a wide array of (semi)groupoids and operations for working with them.
builddeps  :
    - ghc-devel
    - haskell-bifunctors
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
